### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#125]
At the moment there's no way to specify a proxy for http requests. We should add that.

**Comment by djberg96** [comment]
We could set it globally use RestClient.proxy, but I worry that could cause problems with any other code using RestClient. Setting it per-request will be problematic, as the shortcut methods, such as RestClient.get, don't allow for us to set that option. They will all have to be changed to RestClient::Request.execute, and take a hash option.

**Comment by djberg96** [comment]
This was added by https://github.com/ManageIQ/azure-armrest/pull/126 and https://github.com/ManageIQ/azure-armrest/pull/128

**Comment by ogaida** [comment]
It does not work for me. In manageIQ - configuration-Advanced i have set the right Proxy IP and port number for http_proxy for azure, when i use curl with the same proxy settings it works. I can not find any documentation about using a proxy within manageIQ.

**Comment by djberg96** [comment]
@ogaida I know there was an issue with the proxy settings in general recently, but it has since been fixed.

**Comment by djberg96** [comment]
@ogaida Since this issue isn't specific to the azure-armrest gem, can you please create a new issue at the azure provider repo?

https://github.com/ManageIQ/manageiq-providers-azure

**Comment by ogaida** [comment]
@djberg96 Thank you the hint. I opened an issue there [https://github.com/ManageIQ/manageiq-providers-azure/issues/247](https://github.com/ManageIQ/manageiq-providers-azure/issues/247)
