### ISSUE TITLE
Deal with $skip tokens in a uniform manner

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#154]
The recent events stuff has forced us to reconsider how we're wrapping some of the results for various list methods. The problem, in general, is that if you specify a filter of any sort that limits the results, the user may want to get more results from that point on, but there's no way to do that at the moment. This is because the 'nextLink' attribute is not included in the results that we parse.

The solution for Insight::Events that we use, for the moment anyway, is to return an EventList object. It contains the list results (model objects) as one attribute, and the skip token as another.

A couple of ideas to deal with this are:

1) Always return an XList object for all list and list_all methods.

Advantages: It's a clean design. This would make things consistent across the board.
Disadvantages: Causes major breakage. Lots of code would have to be updated for people already using the gem.

2) Return an XList object only if a skip token is found. Otherwise, return a regular list of model objects as we do now.

Advantages: Wouldn't cause breakage for most methods since the 200 limit that applies to events doesn't seem to apply to other resources. Only a filter supplied by the users would generate a skip token.

Disadvantages: Returning different objects based on context is gross. And we couldn't guarantee there wouldn't be any surprises, because it's possible other resources have a default limit that we don't know about.

3) Just add the skip token property on ALL model objects instead of returning a new type of object.

Advantages: This requires minimal change to the code base, and causes no breakage.

Disadvantages: Lots of duplication in the model objects, since it would be identical for all model objects in a particular result set.

Personally I'm leaning towards the last option at the moment, but am open to suggestions.

**Comment by bzwei** [comment]
3) :+1: 
May consider only add skip token to the last object in the list if duplication is a concern.

**Comment by djberg96** [comment]
@bzwei True, we could get the object list first and then do `objects.last['nextLink'] = next_link` within the list and list_all methods.

**Comment by durandom** [comment]
This is how aws does it (see `next_marker`) 
http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#list_objects-instance_method

And here for the API:
http://docs.aws.amazon.com/sdkforruby/api/index.html#Paging_Responses

So, they dont have a `list` and `list_all` method, but  handle the paging inside the sdk in case you are using an enumerator or via `.next_page` if not.

I would go for 3) too. But include it in every object returned. In this scenario the user has to handle the paging anyhow, so he has to check if he hit the last object and trigger another `list` request with the skip marker. I guess this does not break the current API and can be released as a minor version.

For the next release you might consider doing something similar as AWS and deprecate the `list_all` method, handle paging transparently if using a block and return a custom response object (with `.next_page`) which includes `Enumerable`

**Comment by djberg96** [comment]
This was effectively added in https://github.com/ManageIQ/azure-armrest/pull/180.
