### ISSUE TITLE
cannot create storage account

### ISSUE THREAD

**Issue by bzwei** [ManageIQ/azure-armrest#156]
Failed to create a storage account using `StorageAccountService`

First, the default options `{}` is useless because it will fail later on.
Second, `NoMethodError: undefined method 'proxy=' for nil:NilClass`

**Comment by bzwei** [comment]
In the code example, `:location => 'West US'` is not valid. Use `westus`

**Comment by djberg96** [comment]
@bzwei Ok, I can fix the example, and remove the default arguments.

However, I'm not sure I understand the error. How is the create method returning nil?

**Comment by djberg96** [comment]
As per my offline discussions with @bzwei, the fundamental issue is that StorageAccountService#create doesn't generate a response body, unlike every other service we've seen. The result is that the ResourceGroupBasedService#create method is returning nil, which is causing this failure.

**Comment by djberg96** [comment]
Solved with https://github.com/ManageIQ/azure-armrest/pull/157
