### ISSUE TITLE
Nav collapses after clicking on tertiary item

### ISSUE THREAD

**Issue by epwinchell** [ManageIQ/azure-armrest#170]
The Nav should remain fully expanded after clicking on a tertiary item and should close only when hovering off the nav.

**Comment by epwinchell** [comment]
@miq-bot assign @skateman

**Comment by epwinchell** [comment]
@miq-bot add_label ui, bug

**Comment by epwinchell** [comment]
cc @serenamarie125 @jphillips

**Comment by serenamarie125** [comment]
@epwinchell The nav should close when hovering off the nav OR if they click on the pin/collapse icon at the top of the tertiary nav panel.

**Comment by epwinchell** [comment]
wrong repo...

**Comment by epwinchell** [comment]
@miq-bot remove_label bug
