### ISSUE TITLE
Add a resource_group property to TemplateDeployment model objects

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#173]
Although deployments are compartmentalized by resource group, the properties for TemplateDeployment model objects returned by the REST API do not include a resourceGroup property.

Would it be alright to add one? We could parse it out of the ID field.

Overall this would make life a bit easier for MIQ inventory collection.

**Comment by bzwei** [comment]
@djberg96 yes we could. Is there a need for adding resource group?

**Comment by djberg96** [comment]
@bzwei I think it would make life easier for the refresh parser in MIQ, since it doesn't have a location.

**Comment by bzwei** [comment]
@djberg96 go ahead to add the feature if needed. I thought resource group does not help in MIQ refresh as it now looks for resource.

**Comment by djberg96** [comment]
Nevermind, we already have this in the base model. I got myself confused.
