### ISSUE TITLE
Library should store response headers somehow

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#178]
Currently we basically ignore the response headers. However, they may contain useful information:

```
{:cache_control=>"no-cache", :pragma=>"no-cache", :content_type=>"application/json", :content_encoding=>"gzip", :expires=>"-1", :vary=>"Accept-Encoding", :x_ms_request_id=>"a7e0e1ad-6f3a-4eeb-ace8-9c77c3377179", :server=>"Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0", :x_ms_ratelimit_remaining_subscription_reads=>"14872", :x_ms_correlation_request_id=>"a7e0e1ad-6f3a-4eeb-ace8-9c77c3377179", :x_ms_routing_request_id=>"NORTHCENTRALUS:20160601T182659Z:a7e0e1ad-6f3a-4eeb-ace8-9c77c3377179", :strict_transport_security=>"max-age=31536000; includeSubDomains", :date=>"Wed, 01 Jun 2016 18:26:59 GMT", :connection=>"close"}
```

Notably, the `:x_ms_ratelimit_remaining_subscription_reads` would be useful to know, especially if we get close to zero.

I'm not sure how these should be stored, though. Storing header information in the model objects would be wasteful since it would be identical in every object. Perhaps a singleton that stores the header information? I'm open to suggestions.

**Comment by bzwei** [comment]
How are we going to use this information? If we are not sure at this moment, we should postpone the design. I am wondering the header info could be per subscription, per service type, or per call, so it is hard to decide where to store. In addition the header contains multiple keys, each could have different scope, making it harder to be processed in a single way.
I think we can parse the header as needed, not blindly store them all.

**Comment by djberg96** [comment]
@bzwei I think the plan is to use as a way to throttle requests, or rescue failed requests, when the limit is approaching zero.

Perhaps we could leverage the ArmrestCollection class that we added originally for events and continuation token storage, and add a `:headers` attribute. While this would only work for `list` and `list_all` methods, and think that's where it would be most useful anyway, and it would mean storing it once per collection set, rather than once per model.

**Comment by djberg96** [comment]
While I think this is still a good idea, the main culprit is list_private_images. What we need is list_all_private_images, which would reduce multiple calls (one per resource group) down to a single call.

**Comment by djberg96** [comment]
https://github.com/ManageIQ/azure-armrest/pull/180
