### ISSUE TITLE
All url sent by RestClient should be encoded

### ISSUE THREAD

**Issue by bzwei** [ManageIQ/azure-armrest#183]
This is a follow-up with #182. 
All url sent by RestClient should be encoded.

**Comment by djberg96** [comment]
rest-client already does I believe.

**Comment by bzwei** [comment]
Unfortunately no. http://stackoverflow.com/questions/20254749/restclient-parsing-uri-with-space-on-request-path

**Comment by bzwei** [comment]
fixed by #184
