### ISSUE TITLE
TemplateDeploymentService#get_template bug

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#264]
I hit this bug in our current dev environment. You can reproduce it like so:

```
tds = Azure::Armrest::TemplateDeploymentService.new(conf)
tds.get_template("gswmonz1319", "gswmonz1319")
```

Result:

```
/Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:166:in `const_defined?': wrong constant name Openshift webconsole (NameError)
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:166:in `nested_object'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:157:in `block in __setobj__'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:149:in `each'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:149:in `__setobj__'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:67:in `initialize'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:170:in `new'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:170:in `nested_object'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:157:in `block in __setobj__'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:149:in `each'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:149:in `__setobj__'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/model/base_model.rb:67:in `initialize'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/template_deployment_service.rb:50:in `new'
	from /Users/djberge/Dev/azure-armrest-djberg96/lib/azure/armrest/template_deployment_service.rb:50:in `get_template'
	from futz/template.rb:14:in `block in <main>'
	from futz/template.rb:10:in `each'
	from futz/template.rb:10:in `<main>'
```

I'm guessing it's because of the space in the name between "Openshift" and "web console".

Possibly the cause of: https://bugzilla.redhat.com/show_bug.cgi?id=1434988

**Comment by djberg96** [comment]
I'm actually wondering now why we return a model object instead of the raw template there.

**Comment by bzwei** [comment]
@djberg96 Good point. This is the a new method added recently. Indeed we may not want to model it. Can you try to add it the exclude list in https://github.com/ManageIQ/azure-armrest/blob/master/lib/azure/armrest/model/base_model.rb#L211?

**Comment by bzwei** [comment]
Actually should not be in the exclude list. https://github.com/ManageIQ/azure-armrest/blob/master/lib/azure/armrest/template_deployment_service.rb#L50 we should model `DeploymentTemplate`.

**Comment by djberg96** [comment]
Perhaps it was a bad decision, but I'd like to keep backwards compatibility. Please see: https://github.com/ManageIQ/azure-armrest/pull/265

**Comment by bzwei** [comment]
@djberg96 although #265 addresses a potential issue for modeling, it does not solve the problem for deployment template. The template may not be deployed properly if the content has been changed.

We have to make the change here even if it breaks the backward compatibility.

**Comment by djberg96** [comment]
@bzwei Ah, true enough. Ok, I'll modify `get_template` as well then.

**Comment by djberg96** [comment]
@bzwei Actually, that shouldn't modify the content, since the json is stored as its own attribute and `__setobj__(@hash.dup)` uses a dup.

**Comment by bzwei** [comment]
@djberg96 our current implementation of `to_s` is not correct because it does not pickup any changes through setter methods.

**Comment by djberg96** [comment]
Fixed by https://github.com/ManageIQ/azure-armrest/pull/266.
