### ISSUE TITLE
ArmrestManager Locations method need to filter out invalid locations

### ISSUE THREAD

**Issue by bronaghs** [ManageIQ/azure-armrest#38]
When some locations such as BrazilSouth or AustraliaEast are passed into the VMM.Series method they cause the follow error:

"https://management.azure.com/subscriptions/462f2af8-e67e-40c6-9fbf-02824d1dd485/providers/Microsoft.Compute/locations/AustraliaEast/vmSizes?api-version=2015-06-15"
/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 502 Bad Gateway (RestClient::BadGateway)
	from /opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /opt/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
	from /Users/bronaghsorota/dev/azure-armrest/lib/azure/armrest/armrest_manager.rb:356:in `rest_get'
	from /Users/bronaghsorota/dev/azure-armrest/lib/azure/armrest/virtual_machine_manager.rb:58:in `series'
	from ./july17test.rb:29:in `block in <main>'
	from ./july17test.rb:27:in `each'
	fr

**Comment by djberg96** [comment]
I'll ask about this, but I suspect our best bet is to explicitly catch the bad gateway error and return nil or an empty array.

**Comment by djberg96** [comment]
Actually, I think it will always do that if the location you provide isn't among the locations returned by the locations method for the current provider. So this will do the same thing:

```vmm.series('bogus')```

I guess the question is whether or not we should validate the location within the method first.

**Comment by bronaghs** [comment]
@djberg96 I am passing the results of the locations method into the series method and it bombs out on a bunch of them

**Comment by djberg96** [comment]
As discussed on IRC (for anyone watching), some of the locations had parens in them, so we had to parse them out.
