### ISSUE TITLE
Parallel dependency 5y old

### ISSUE THREAD

**Issue by nouseforaname** [ManageIQ/azure-armrest#421]
Hi,

While evaluating your gem I noticed that it seems to have some very outdated dependencies. While it does provide the required functionality I'm looking for, I'm a bit worried about the age of some of the dependencies. I briefly looked into creating a PR for a bump but it seems that it's locked by 
```
    manageiq-style was resolved to 1.3.2, which depends on
      rubocop (~> 1.13) was resolved to 1.32.0, which depends on
        parallel (~> 1.10)
```

Any chance for a dependency bump on this?

**Comment by agrare** [comment]
:+1: great catch @nouseforaname I'm not sure why this had such a restrictive version requirement.  Opened a PR to bump this.

**Comment by djberg96** [comment]
I think we were bouncing back and forth between stricter and looser version requirements for a while back in the day. As long as it works, I'm fine with it. :)

**Comment by agrare** [comment]
@nouseforaname I've released v0.15.0 with this change

**Comment by nouseforaname** [comment]
<3 thank you

**Comment by Fryguy** [comment]
@nouseforaname totally unrelated, I love your GitHub handle 🤘

😉 https://en.wikipedia.org/wiki/No_Use_for_a_Name  cc @jrafanie

**Comment by jrafanie** [comment]
> @nouseforaname totally unrelated, I love your GitHub handle 🤘
> 
> 😉 [en.wikipedia.org/wiki/No_Use_for_a_Name](https://en.wikipedia.org/wiki/No_Use_for_a_Name) cc @jrafanie

That's a Sly handle

**Comment by nouseforaname** [comment]
I was somewhat surprised that it was still free back then. :)
