### ISSUE TITLE
Code reorganization

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#45]
After my small break and looking at this code again, I'm wondering if we should separate out some of the integrated methods into their own manager classes, such as:

* SubscriptionManager
* ResourceManager
* LinkedResourceManager
* ResourceGroupManager
* ResourceProviderManager
* TenantManager
* TagManager
* TemplateDeploymentManager

Then use those classes internally for various functions.

What do you think?

**Comment by blomquisg** [comment]
I don't really know the ARM API, but it seems like 

> * ResourceManager
> * LinkedResourceManager
> * ResourceGroupManager
> * ResourceProviderManager

... is a lot of fine grained division of things that sound like resource management.  Could all of that be under `ResourceManager`?

**Comment by djberg96** [comment]
I'm more or less trying to match the way they've organized their API online. I was thinking those others would be subclasses of ResourceManager to try to keep the class from getting too tall.

We can always merge them initially and split them out later if we feel that makes more sense later.

**Comment by blomquisg** [comment]
Sure.   It's mainly just a kneejerk reaction to a bunch of things called `Resource"Something` and wondering if those all belong together.

**Comment by djberg96** [comment]
We've basically done this, so closing.
