### ISSUE TITLE
When determining api versions for providers, case should be ignored

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/azure-armrest#70]
I ran into an issue where I had set my provider to "Microsoft.Insights" instead of "microsoft.insights". Because it wasn't an exact match it returned the default api version, which it turns out didn't work.

I think the set_service_api_version and/or set_providers_info methods should be adjusted so that they ignore case, since MS ignores the provider's case as well.

**Comment by bzwei** [comment]
Fixed in #72
